### PR TITLE
Solved Issue in Hiding the Border in stats 

### PR DESCRIPTION
**Pull request by khalidk799**
Use this to hide the border 
&&hide_border=true

Thanks 
K.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Hey there,

I believe the issue is about hiding the table borders, not the border on the stats embed.

**Comment by SashoStoichkov** [comment]
Sorry, but the issue is about hiding the table borders.

Thanks anyway 👍🏻

**Comment by khalidk799** [comment]
Sorry, Understood it wrong

**Comment by SashoStoichkov** [comment]
No problem 🤓

**Pull request closed without merging**
